# Required since Travis-CI Python 3.7 support is currently bad
# See https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
language: python
sudo: required
dist: xenial
python: "3.7"
install:
  - pip install -r requirements.txt
script:
  - ./lint.sh
  - ./run_tests.sh
